apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: bookstore-orders-pipelinerun-trigger-template
spec:
  params:
  - name: git-repo-url
    description: The git repository url
# - name: git-branch
#   description: The git revision    
  - name: git-commit-id
    description: The name of the deployment to be created / patched
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: bookstore-orders-pipelinerun-
    spec:
      pipelineRef:
        name: bookstore-orders-pipeline
      params:
      - name: CODE_REPO_URL
        value: $(tt.params.git-repo-url)
#     - name: CODE_REPO_BRANCH
#       value: $(tt.params.git-branch)
      - name: CODE_REPO_COMMIT_ID
        value: $(tt.params.git-commit-id) 
      workspaces:
        - name: bookstore-orders-workspace
          persistentVolumeClaim:
            claimName: bookstore-orders-pvc