apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: argocd-sync-and-wait
spec:
  params:
    - name: application-name
      description: name of the application to sync
    - name: revision
      description: the revision to sync to
      default: HEAD
    - name: flags
      default: --
    - name: argocd-version
      default: v2.2.1
    - name: argocd-server
      default: argocd-server.argocd.svc:80      
    - name: username
      default: admin
    - name: password
      default: '' 
  steps:
    - name: login
      image: docker.io/argoproj/argocd:$(params.argocd-version)
      script: |        
        yes y | argocd login --insecure "$(params.argocd-server)" --username="$(params.username)" --password="$(params.password)";        
        argocd app sync "$(params.application-name)" --revision "$(params.revision)" "$(params.flags)";
        argocd app wait "$(params.application-name)" --health "$(params.flags)"