kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: tekton-pipeline-cluster-role-binding

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-pipeline-cluster-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: bookstore-pipelines
# namespace: <your-namespace-name>
  