apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookstore-orders-pvc
  labels:
    app: bookstore-orders
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi