apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookstore-user-pvc
  labels:
    app: bookstore-user
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi