apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookstore-book-pvc
  labels:
    app: bookstore-book
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi