apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: bookstore-pipelinerun-trigger-binding
spec:
  params:
  - name: git-repo-url
    value: $(body.repository.clone_url)
# - name: git-branch
#   value: $(body.ref)
  - name: git-commit-id
    value: $(body.commits[0].id)