apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: bookstore-ui-event-listener
spec:
  triggers:  
    - bindings:
        - kind: TriggerBinding
          ref: bookstore-pipelinerun-trigger-binding
      template:
        ref: bookstore-ui-pipelinerun-trigger-template
  
#   - bindings:
#       - kind: TriggerBinding
#         ref: bookstore-pipelinerun-trigger-binding
#     template:
#       ref: bookstore-ui-pipelinerun-trigger-template-dev
#     interceptors:
#       - cel:
#           filter: >-
#             body.ref.startsWith('refs/heads/dev') 
#
#   - bindings:
#       - kind: TriggerBinding
#         ref: bookstore-pipelinerun-trigger-binding
#     template:
#       ref: bookstore-ui-pipelinerun-trigger-template-qa
#     interceptors:
#       - cel:
#           filter: >-
#             body.ref.startsWith('refs/heads/qa') 
#
#   - bindings:
#       - kind: TriggerBinding
#         ref: bookstore-pipelinerun-trigger-binding
#     template:
#       ref: bookstore-ui-pipelinerun-trigger-template-prod
#     interceptors:
#       - cel:
#           filter: >-
#             body.ref.startsWith('refs/heads/master')        
