apiVersion: v1
kind: Service
metadata:
  name: bookstore-orders
  namespace: bookstore
spec:
  type: NodePort
  ports:
  - port: 8082
    targetPort: 8082
    nodePort: 30073
  selector:
    app: bookstore-orders
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-orders
  namespace: bookstore
spec:
  selector:
    matchLabels:
      app: bookstore-orders
  strategy:
    type: Recreate
  revisionHistoryLimit: 0  
  template:
    metadata:
      labels:
        app: bookstore-orders
    spec:
      containers:
      - image: vkyepuri/bookstore-orders:latest
        name: bookstore-orders
        env:          
        - name: BS_ORDER_DBHOST
          value: mysql.bookstore.svc.cluster.local
        - name: BS_ORDER_DBNAME
          value: bookstore
        - name: BS_ORDER_DB_USERNAME
          value: root           
        - name: BS_ORDER_DB_PASSWORD
          value: Root_12345
        - name: USER_SVC_ROLE_URL
          value: http://bookstore-user.bookstore.svc.cluster.local:8080/user/role 
        - name: BOOK_QUANTITY_UPDATE_URL
          value: http://bookstore-book.bookstore.svc.cluster.local:8081/books/updatequantity          
        ports:
        - containerPort: 8082
          name: orders