apiVersion: v1
kind: Service
metadata:
  name: bookstore-book
  namespace: bookstore
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30072
  selector:
    app: bookstore-book
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-book
  namespace: bookstore
spec:
  selector:
    matchLabels:
      app: bookstore-book
  strategy:
    type: Recreate
  revisionHistoryLimit: 0  
  template:
    metadata:
      labels:
        app: bookstore-book
    spec:
      containers:
      - image: vkyepuri/bookstore-book:latest
        name: bookstore-book
        env:          
        - name: BS_BOOK_DB_DRIVER
          value: com.mysql.cj.jdbc.Driver
        - name: BS_BOOK_DB_URL
          value: jdbc:mysql://mysql.bookstore.svc.cluster.local:3306/bookstore
        - name: BS_BOOK_DB_USERNAME
          value: root
        - name: BS_BOOK_DB_PASSWORD
          value: Root_12345
        - name: USER_SVC_ROLE_URL
          value: http://bookstore-user.bookstore.svc.cluster.local:8080/user/role
        ports:
        - containerPort: 8081
          name: book