apiVersion: v1
kind: Service
metadata:
  name: bookstore-user
  namespace: bookstore
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30071
  selector:
    app: bookstore-user
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-user
  namespace: bookstore
spec:
  selector:
    matchLabels:
      app: bookstore-user
  strategy:
    type: Recreate
  revisionHistoryLimit: 0  
  template:
    metadata:
      labels:
        app: bookstore-user
    spec:
      containers:
      - image: vkyepuri/bookstore-user:latest
        name: bookstore-user
        env:          
        - name: BS_USER_DB_DRIVER
          value: com.mysql.cj.jdbc.Driver
        - name: BS_USER_DB_URL
          value: jdbc:mysql://mysql.bookstore.svc.cluster.local:3306/bookstore
        - name: BS_USER_DB_USERNAME
          value: root
        - name: BS_USER_DB_PASSWORD
          value: Root_12345           
        ports:
        - containerPort: 8080
          name: user
